apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: platform
  namespace: openshift-tracing
spec:
  observability:
    metrics:
      enableMetrics: true
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token

    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    connectors:
      spanmetrics:
        dimensions:
        - name: k8s.namespace.name

    processors:
      k8sattributes: {}

    exporters:
      otlp:
        endpoint: tempo-platform-gateway.openshift-tracing.svc.cluster.local:8090
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: platform
      prometheus:
        endpoint: 0.0.0.0:8889

    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          processors: []
          exporters: [prometheus]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-traces-writer
rules:
- apiGroups: [tempo.grafana.com]
  resources: [platform]
  resourceNames: [traces]
  verbs: [create]
---
# allow platform-collector to write traces to Tempo
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-traces-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-traces-writer
subjects:
- kind: ServiceAccount
  name: platform-collector
  namespace: openshift-tracing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-collector
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
# allow platform-collector to read namespaces, pods and replicasets (required for k8sattributes processor)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-collector
roleRef:
  kind: ClusterRole
  name: platform-collector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: platform-collector
  namespace: openshift-tracing
