apiVersion: tempo.grafana.com/v1alpha1
kind:  TempoStack
metadata:
  name: platform
  namespace: openshift-tracing
spec:
  storage:
    secret:
      name: minio
      type: s3
  storageSize: 1Gi
  tenants:
    mode: openshift
    authentication:
    - tenantName: platform
      tenantId: 1610b0c3-c509-4592-a256-a1871353dbfa
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-traces-reader
rules:
- apiGroups: [tempo.grafana.com]
  resources: [platform]
  resourceNames: [traces]
  verbs: [get]
---
# allow any authenticated user to read traces from Tempo
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-traces-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-traces-reader
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
