{{- if and .Values.ui.traces.enabled (eq .Values.ui.traces.version "development") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: distributed-tracing-console-plugin
  namespace: openshift-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributed-tracing-console-plugin
rules:
- apiGroups: ["tempo.grafana.com"]
  resources: ["tempostacks", "tempomonolithics"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: distributed-tracing-console-plugin
subjects:
- kind: ServiceAccount
  name: distributed-tracing-console-plugin
  namespace: openshift-observability
roleRef:
  kind: ClusterRole
  name: distributed-tracing-console-plugin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: distributed-tracing-console-plugin
  namespace: openshift-observability
  labels:
    app: distributed-tracing-console-plugin
    app.kubernetes.io/component: distributed-tracing-console-plugin
    app.kubernetes.io/instance: distributed-tracing-console-plugin
    app.kubernetes.io/part-of: distributed-tracing-console-plugin
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: distributed-tracing-console-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-tracing-console-plugin
  namespace: openshift-observability
  labels:
    app: distributed-tracing-console-plugin
    app.kubernetes.io/component: distributed-tracing-console-plugin
    app.kubernetes.io/instance: distributed-tracing-console-plugin
    app.kubernetes.io/part-of: distributed-tracing-console-plugin
    app.openshift.io/runtime-namespace: openshift-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-tracing-console-plugin
  template:
    metadata:
      labels:
        app: distributed-tracing-console-plugin
    spec:
      serviceAccountName: distributed-tracing-console-plugin
      containers:
        - name: distributed-tracing-console-plugin
          image: quay.io/agerstmayr/distributed-tracing-console-plugin:latest
          args:
            - "-port=9443"
            - "-cert=/var/serving-cert/tls.crt"
            - "-key=/var/serving-cert/tls.key"
            - "-plugin-config-path=/etc/plugin/config.yaml"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: plugin-config
              readOnly: true
              mountPath: /etc/plugin/config.yaml
              subPath: config.yaml
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        - name: plugin-config
          configMap:
            name: distributed-tracing-console-plugin-config
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: distributed-tracing-console-plugin
  namespace: openshift-observability
spec:
  displayName: "Distributed Tracing Console Plugin"
  backend:
    type: Service
    service:
      name: distributed-tracing-console-plugin
      namespace: openshift-observability
      basePath: "/"
      port: 9443
  proxy:
  - alias: backend
    authorization: UserToken
    endpoint:
      service:
        name: distributed-tracing-console-plugin
        namespace: openshift-observability
        port: 9443
      type: Service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: distributed-tracing-console-plugin-config
  namespace: openshift-observability
  labels:
    app: distributed-tracing-console-plugin
    app.kubernetes.io/part-of: distributed-tracing-console-plugin
data:
  config.yaml: |-
    logsLimit: 100
    timeout: "30s"
{{- end }}
