services:
  distributor:
    image: &tempoImage grafana/tempo:latest
    command: "-target=distributor -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "4318:4318"   # otlp-http
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  ingester-0:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  ingester-1:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  ingester-2:
    image: *tempoImage
    command: "-target=ingester -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  query-frontend:
    image: *tempoImage
    command: "-target=query-frontend -config.file=/etc/tempo.yaml -log.level=debug"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  querier:
    image: *tempoImage
    command: "-target=querier -config.file=/etc/tempo.yaml -log.level=debug"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  compactor:
    image: *tempoImage
    command: "-target=compactor -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  metrics-generator:
    image: *tempoImage
    command: "-target=metrics-generator -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318

  tempo-query:
    image: grafana/tempo-query:latest
    environment:
    - BACKEND=query-frontend:3200

  jaeger-query:
    image: docker.io/jaegertracing/jaeger-query:1.62.0
    command:
    - --query.base-path=/
    - --span-storage.type=grpc
    - --grpc-storage.server=tempo-query:7777
    - --query.bearer-token-propagation=true
    ports:
    - "16686:16686"

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=tempo
      - MINIO_SECRET_KEY=supersecret
    #ports:
    #  - "9001:9001"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/tempo && minio server /data --console-address ':9001'

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.5
    environment:
      - ENDPOINT=otel:4317
    restart: always

  hotrod:
    image: jaegertracing/example-hotrod:1.46
    command: all --otel-exporter=otlp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.2.2
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    ports:
      - "3001:3000"

  otel:
    image: ghcr.io/os-observability/redhat-opentelemetry-collector/redhat-opentelemetry-collector:latest
    volumes:
      - ./otel.yaml:/etc/otelcol/config.yaml
