{{- if .Values.storage.traces.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openshift-tracing-s3
  namespace: openshift-observability
stringData:
  endpoint: {{ .Values.storage.s3.endpoint }}
  bucket: {{ .Values.storage.traces.storage.s3.bucket }}
  access_key_id: {{ .Values.storage.s3.access_key_id }}
  access_key_secret: {{ .Values.storage.s3.access_key_secret }}
{{- end }}
