{{- if and .Values.korrel8r.enabled .Values.cluster_observability_operator.enabled }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: troubleshooting-panel
spec:
  type: TroubleshootingPanel
{{- end }}
