{{- if .Values.collection.otlp.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  namespace: openshift-observability
spec:
  exporter:
    endpoint: http://otlp-collector.openshift-observability:4317
  sampler:
    type: parentbased_always_on
{{- end }}
