{{- if .Values.grafana.enabled }}
# read logs and traces from 'application' tenant
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-observability-grafana
rules:
- apiGroups: [loki.grafana.com]
  resourceNames: [logs]
  verbs: [get]
  resources: [application]
- apiGroups: [tempo.grafana.com]
  resourceNames: [traces]
  verbs: [get]
  resources: [application]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-observability-grafana
roleRef:
  kind: ClusterRole
  name: openshift-observability-grafana
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: openshift-observability
---
# Grant the ServiceAccount view permissions of the openshift-observability namespace.
# If the ServiceAccount cannot access any namespaces, every 'get' request will be denied:
# https://github.com/observatorium/opa-openshift/pull/18/files
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-sa-view
  namespace: openshift-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: openshift-observability
{{- end}}
