{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: grafana-sa
  namespace: openshift-observability
  annotations:
    # this annotation generates a token for the service account and stores it in this secret under the "token" key
    kubernetes.io/service-account.name: grafana-sa
{{- end}}
