apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: demo
  namespace: tempo-examples
spec:
  observability:
    metrics:
      enableMetrics: true
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    connectors:
      spanmetrics:
        metrics_flush_interval: 5s # default: 1 min
        dimensions:
        - name: k8s.namespace.name

    processors:
      k8sattributes: {}

    exporters:
      otlp:
        endpoint: tempo-demo-gateway.tempo-examples.svc.cluster.local:8090
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: tenant1
      prometheus:
        endpoint: 0.0.0.0:8889
        add_metric_suffixes: false
        resource_to_telemetry_conversion:
          enabled: true # by default resource attributes are dropped

    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          processors: []
          exporters: [prometheus]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempo-examples-demo-collector
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
# allow demo-collector to read namespaces, pods and replicasets (required for k8sattributes processor)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempo-examples-demo-collector
roleRef:
  kind: ClusterRole
  name: tempo-examples-demo-collector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: demo-collector
  namespace: tempo-examples

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traces-writer-tenant1
rules:
- apiGroups: [tempo.grafana.com]
  resources: [tenant1]
  resourceNames: [traces]
  verbs: [create]
---
# allow demo-collector to write traces to the 'tenant1' tenant in Tempo
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traces-writer-tenant1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traces-writer-tenant1
subjects:
- kind: ServiceAccount
  name: demo-collector
  namespace: tempo-examples
