apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tracing-app-photo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: user-workload-instrumentation
    spec:
      containers:
      - name: frontend
        image: quay.io/agerstmayr/tracing-demo-frontend:0.6.0
        env:
        - name: BACKEND
          value: http://backend:5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tracing-app-photo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - port: 5173
    targetPort: 5173
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: tracing-app-photo
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 5173
