{{- if .Values.traces.enabled }}
apiVersion: tempo.grafana.com/v1alpha1
kind:  TempoStack
metadata:
  name: openshift-tracing
  namespace: openshift-observability
spec:
  storage:
    secret:
      name: tempo-storage
      type: s3
  storageSize: 1Gi
  tenants:
    mode: openshift
    authentication:
    - tenantName: default-tenant
      tenantId: default-tenant
  #observability:
  #  tracing:
  #    jaeger_agent_endpoint: platform-collector.openshift-tracing:6831
  #    sampling_fraction: "1"
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true
        monitorTab:
          enabled: true 
          prometheusEndpoint: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
---
apiVersion: v1
kind: Secret
metadata:
  name: tempo-storage
  namespace: openshift-observability
stringData:
  endpoint: {{ .Values.storage.s3.endpoint }}
  bucket: {{ .Values.traces.storage.s3.bucket }}
  access_key_id: {{ .Values.storage.s3.access_key_id }}
  access_key_secret: {{ .Values.storage.s3.access_key_secret }}
type: Opaque
{{- end }}
