{{- if and .Values.traces.enabled .Values.traces.ui.enabled .Values.cluster_observability_operator.enabled (ne .Values.traces.ui.version "development") }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: distributed-tracing
spec:
  type: DistributedTracing
{{- end }}
