apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
  observability:
    metrics:
      enableMetrics: true # the operator will create a ServiceMonitor to scrape metrics exported by the prometheus exporter
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.117.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831

    connectors:
      spanmetrics:
        metrics_flush_interval: 5s # default: 1 min
        dimensions:
        - name: k8s.namespace.name

    processors:
      k8sattributes: {}

    exporters:
      otlphttp:
        endpoint: http://tempo-tempo1-distributor.tempo:4318
      prometheus:
        endpoint: 0.0.0.0:8889
        add_metric_suffixes: false
        resource_to_telemetry_conversion:
          enabled: true # by default resource attributes are dropped

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [k8sattributes]
          exporters: [otlphttp, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          processors: []
          exporters: [prometheus]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-otel-collector
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
# allow otel-collector to read namespaces, pods and replicasets (required for k8sattributes processor)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-otel-collector
roleRef:
  kind: ClusterRole
  name: opentelemetry-otel-collector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: opentelemetry
