apiVersion: v1
kind: Namespace
metadata:
  name: tempo
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo1
  namespace: tempo
spec:
  storage:
    secret:
      name: minio
      type: s3
  storageSize: 1Gi
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: tempo
stringData:
  endpoint: http://minio.minio:9000
  bucket: tempo
  access_key_id: tempo
  access_key_secret: supersecret
type: Opaque
