apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo1
  namespace: tracing
spec:
  storage:
    secret:
      name: minio
      type: s3
  storageSize: 1Gi
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
