apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo1
  namespace: tracing
spec:
  storage:
    secret:
      name: minio
      type: s3
  storageSize: 1Gi
  observability:
    tracing:
      otlp_http_endpoint: http://otel-collector:4318
      sampling_fraction: "1"
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
