{{- if .Values.demo.telemetrygen }}
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app-telemetrygen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: telemetrygen
  name: telemetrygen
  namespace: demo-app-telemetrygen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telemetrygen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telemetrygen
    spec:
      containers:
      # Metrics
      # this generates 1 metric value for the 'gen' metric every 10 seconds
      - name: metricsgen1
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0
        args:
          - metrics
          - --otlp-endpoint=telemetry-collector.openshift-observability:4317
          - --otlp-insecure
          - --duration=1h
          - --rate=0.1 # metrics per second

      # Logs
      # this generates 1 log message ("body":"the message") every 10 seconds
      - name: logsgen1
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0
        args:
          - logs
          - --otlp-endpoint=telemetry-collector.openshift-observability:4317
          - --otlp-insecure
          - --duration=1h
          - --rate=0.1 # logs per second

      # Traces
      # in total 5 spans per second are generated, with 2/5 (40%) containing an error
      # this generates 3 spans per second
      - name: tracegen1
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0
        args:
          - traces
          - --otlp-endpoint=telemetry-collector.openshift-observability:4317
          - --otlp-insecure
          - --duration=1h
          - --service=telemetrygen-good
          - --rate=3 # spans per second
          - --child-spans=2
      # this generates 2 spans per second with an error status
      - name: tracegen2
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0
        args:
          - traces
          - --otlp-endpoint=telemetry-collector.openshift-observability:4317
          - --otlp-insecure
          - --duration=1h
          - --service=telemetrygen-faulty
          - --rate=2 # spans per second
          - --child-spans=1
          - --status-code=Error
{{- end }}
