{{- if .Values.storage.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: openshift-observability
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app.kubernetes.io/name: minio
  type: ClusterIP
{{- end }}
